[package]
name = "ncmmiao"
version = "2.8.20"
edition = "2021"
authors = ["Lkhsss <lkhsss1019@gmail.com>"]
description = "A magic tool convert ncm to flac"
repository = "https://github.com/lkhsss/ncmmiao"
license = "GPL-3.0-or-later"
keywords = ["ncm", "flac", "neteasemusic"]


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aes = { version = "0.8.4", default-features = false }
audiotags = { version = "0.5.0", default-features = false }
base64 = { version = "0.22.*" }
chrono = { version = "0.4.*", features = ["clock"], default-features = false }
clap = { version = "4.5.*", features = ["derive", "std"] }
colored = { version = "3.0.0", default-features = false }
crossbeam-channel = "0.5.15"
env_logger = { version = "0.11.7", default-features = false }
image = "0.25.*"
indicatif = "0.17.9"
lazy_static = "1.5.0"
log = "0.4.20"
num_cpus = "1.17.0"
serde = { version = "1.0.195", features = ["derive"] }
serde_derive = "1.0.*"
serde_json = "1.0.*"
walkdir = "2.4.*"

[badges]
maintenance = { status = "actively-developed" }

[profile.release]
#缩小编译后体积
strip = true
# strip = "debuginfo" #仅移除debug信息
lto = true      #启用链接时间优化
panic = "abort" #panic时直接abort
opt-level = "z" #优化级别
